### ISSUE TITLE
pyside2

### ISSUE THREAD

**Issue by electrocoder** [ilkermanap/pyqt#1]
İlker Bey elinize sağlık. pyside2 için güncelleme yapmayı planlıyormusunuz?

**Comment by ilkermanap** [comment]
Merhaba, tum ornekleri pyside2 ile degistirip  guncelleyecegim. Su sira baska projeler vaktimin cogunu aliyor. O yuzden bu islem cabuk olmayabilir. 

Dokumana  katki yapmak isterseniz, merge ettigim zaman otomatik olarak  yayina aktariliyor.

**Comment by ilkermanap** [comment]
pyside2 icin dokuman ve ornekler guncellendi. 

veri cizimi yapan ornekte kullanilan pyqtgraph henuz pyside2 ile calismadigi icin onu sonraya biraktim.
